### ISSUE TITLE
3ds port

### ISSUE THREAD

**Issue by dona12345** [moonlight-stream/moonlight-common-c#33]
Can someone port moonlight to 3ds?(sorry that this is not an issue but i don't know how to ask it)

**Comment by d3m3vilurr** [comment]
interesting. but 3ds has too small resolution. maybe you couldn't read a text :thinking:

**Comment by mirh** [comment]
400×240 is low yes. 
Though.. I mean, the "we do what we must because we can" feeling is there I guess. 
If not any, there are still DOS games that would be perfect for it /s

But assuming non-infinite time, I'd rather have the thing to expand into supporting more standards.. or even just maintenance for already existing ports
