### ISSUE TITLE
BT.709 and full color range by default

### ISSUE THREAD

**Issue by skbeh** [moonlight-stream/moonlight-common-c#71]
Nowadays, almost all clients are using BT.709 and full color range, and the network usage should be acceptable.
Maybe compatibility of color range was a thing when the library was created, but now every modern tv is able to show contents with full RGB range.
I think it is time to change the defaults.

**Comment by cgutman** [comment]
Those defaults come from NVIDIA GameStream itself (specifically the `encoderCsc` SDP value, which defaults to `0` meaning BT.601 limited range).

I likely won't be changing those here due to compatibility reasons, but clients are free to request whatever colorspace and color range they would like using the `colorSpace` and `colorRange` fields in `STREAM_CONFIGURATION`.

**Comment by skbeh** [comment]
Ok, I think it would be better to discuss it in the moonlight client repos rather than the library.
